# TCL File Generated by Component Editor 18.1
# Thu Jan 13 21:05:09 CET 2022
# DO NOT MODIFY


# 
# Heartrate_Variability "Heartrate" v1.0
#  2022.01.13.21:05:09
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module Heartrate_Variability
# 
set_module_property DESCRIPTION ""
set_module_property NAME Heartrate_Variability
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Heartrate
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL HRV_Avalon
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file clock_divider.vhd VHDL PATH hrv_source/clock_divider.vhd
add_fileset_file HRV_Avalon.vhd VHDL PATH hrv_source/HRV_Avalon.vhd TOP_LEVEL_FILE
add_fileset_file HRV_Avalon_architecture.vhd VHDL PATH hrv_source/HRV_Avalon_architecture.vhd
add_fileset_file HRV_buffer.vhd VHDL PATH hrv_source/HRV_buffer.vhd
add_fileset_file HRV_buffer_architecture.vhd VHDL PATH hrv_source/HRV_buffer_architecture.vhd
add_fileset_file HRV_calculator.vhd VHDL PATH hrv_source/HRV_calculator.vhd
add_fileset_file HRV_calculator_architecture.vhd VHDL PATH hrv_source/HRV_calculator_architecture.vhd
add_fileset_file RR_calculator.vhd VHDL PATH hrv_source/RR_calculator.vhd
add_fileset_file RR_calculator_architecture.vhd VHDL PATH hrv_source/RR_calculator_architecture.vhd
add_fileset_file RR_timer.vhd VHDL PATH hrv_source/RR_timer.vhd
add_fileset_file RR_timer_architecture.vhd VHDL PATH hrv_source/RR_timer_architecture.vhd
add_fileset_file SDRR2_calculator.vhd VHDL PATH hrv_source/SDRR2_calculator.vhd
add_fileset_file SDRR2_calculator_architecture.vhd VHDL PATH hrv_source/SDRR2_calculator_architecture.vhd
add_fileset_file SDRR_calculator.vhd VHDL PATH hrv_source/SDRR_calculator.vhd
add_fileset_file SDRR_calculator_architecture.vhd VHDL PATH hrv_source/SDRR_calculator_architecture.vhd
add_fileset_file moving_average_calculator.vhd VHDL PATH hrv_source/moving_average_calculator.vhd
add_fileset_file moving_average_calculator_architecture.vhd VHDL PATH hrv_source/moving_average_calculator_architecture.vhd
add_fileset_file peak_detector.vhd VHDL PATH hrv_source/peak_detector.vhd
add_fileset_file peak_detector_architecture.vhd VHDL PATH hrv_source/peak_detector_architecture.vhd
add_fileset_file signal_smoother.vhd VHDL PATH hrv_source/signal_smoother.vhd
add_fileset_file signal_smoother_architecture.vhd VHDL PATH hrv_source/signal_smoother_architecture.vhd
add_fileset_file square_root_calculator.vhd VHDL PATH hrv_source/square_root_calculator.vhd
add_fileset_file synchronizer.vhd VHDL PATH hrv_source/synchronizer.vhd
add_fileset_file synchronizer_architecture.vhd VHDL PATH hrv_source/synchronizer_architecture.vhd

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL HRV_Avalon
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file clock_divider.vhd VHDL PATH hrv_source/clock_divider.vhd
add_fileset_file HRV_Avalon.vhd VHDL PATH hrv_source/HRV_Avalon.vhd
add_fileset_file HRV_Avalon_architecture.vhd VHDL PATH hrv_source/HRV_Avalon_architecture.vhd
add_fileset_file HRV_buffer.vhd VHDL PATH hrv_source/HRV_buffer.vhd
add_fileset_file HRV_buffer_architecture.vhd VHDL PATH hrv_source/HRV_buffer_architecture.vhd
add_fileset_file HRV_calculator.vhd VHDL PATH hrv_source/HRV_calculator.vhd
add_fileset_file HRV_calculator_architecture.vhd VHDL PATH hrv_source/HRV_calculator_architecture.vhd
add_fileset_file RR_calculator.vhd VHDL PATH hrv_source/RR_calculator.vhd
add_fileset_file RR_calculator_architecture.vhd VHDL PATH hrv_source/RR_calculator_architecture.vhd
add_fileset_file RR_timer.vhd VHDL PATH hrv_source/RR_timer.vhd
add_fileset_file RR_timer_architecture.vhd VHDL PATH hrv_source/RR_timer_architecture.vhd
add_fileset_file SDRR2_calculator.vhd VHDL PATH hrv_source/SDRR2_calculator.vhd
add_fileset_file SDRR2_calculator_architecture.vhd VHDL PATH hrv_source/SDRR2_calculator_architecture.vhd
add_fileset_file SDRR_calculator.vhd VHDL PATH hrv_source/SDRR_calculator.vhd
add_fileset_file SDRR_calculator_architecture.vhd VHDL PATH hrv_source/SDRR_calculator_architecture.vhd
add_fileset_file moving_average_calculator.vhd VHDL PATH hrv_source/moving_average_calculator.vhd
add_fileset_file moving_average_calculator_architecture.vhd VHDL PATH hrv_source/moving_average_calculator_architecture.vhd
add_fileset_file peak_detector.vhd VHDL PATH hrv_source/peak_detector.vhd
add_fileset_file peak_detector_architecture.vhd VHDL PATH hrv_source/peak_detector_architecture.vhd
add_fileset_file signal_smoother.vhd VHDL PATH hrv_source/signal_smoother.vhd
add_fileset_file signal_smoother_architecture.vhd VHDL PATH hrv_source/signal_smoother_architecture.vhd
add_fileset_file square_root_calculator.vhd VHDL PATH hrv_source/square_root_calculator.vhd
add_fileset_file synchronizer.vhd VHDL PATH hrv_source/synchronizer.vhd
add_fileset_file synchronizer_architecture.vhd VHDL PATH hrv_source/synchronizer_architecture.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink csi_clock_clk clk Input 1


# 
# connection point reset_reset
# 
add_interface reset_reset reset end
set_interface_property reset_reset associatedClock clock_sink
set_interface_property reset_reset synchronousEdges DEASSERT
set_interface_property reset_reset ENABLED true
set_interface_property reset_reset EXPORT_OF ""
set_interface_property reset_reset PORT_NAME_MAP ""
set_interface_property reset_reset CMSIS_SVD_VARIABLES ""
set_interface_property reset_reset SVD_ADDRESS_GROUP ""

add_interface_port reset_reset csi_reset_reset reset Input 1


# 
# connection point clock
# 
add_interface clock conduit end
set_interface_property clock associatedClock clock_sink
set_interface_property clock associatedReset ""
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock hrv_clock export Input 1


# 
# connection point heartbeat_data
# 
add_interface heartbeat_data conduit end
set_interface_property heartbeat_data associatedClock clock_sink
set_interface_property heartbeat_data associatedReset ""
set_interface_property heartbeat_data ENABLED true
set_interface_property heartbeat_data EXPORT_OF ""
set_interface_property heartbeat_data PORT_NAME_MAP ""
set_interface_property heartbeat_data CMSIS_SVD_VARIABLES ""
set_interface_property heartbeat_data SVD_ADDRESS_GROUP ""

add_interface_port heartbeat_data heartbeat_data export Input 16


# 
# connection point stress_level_1
# 
add_interface stress_level_1 avalon end
set_interface_property stress_level_1 addressUnits SYMBOLS
set_interface_property stress_level_1 associatedClock clock_sink
set_interface_property stress_level_1 associatedReset reset_reset
set_interface_property stress_level_1 bitsPerSymbol 8
set_interface_property stress_level_1 burstOnBurstBoundariesOnly false
set_interface_property stress_level_1 burstcountUnits WORDS
set_interface_property stress_level_1 explicitAddressSpan 0
set_interface_property stress_level_1 holdTime 0
set_interface_property stress_level_1 linewrapBursts false
set_interface_property stress_level_1 maximumPendingReadTransactions 0
set_interface_property stress_level_1 maximumPendingWriteTransactions 0
set_interface_property stress_level_1 readLatency 0
set_interface_property stress_level_1 readWaitTime 1
set_interface_property stress_level_1 setupTime 0
set_interface_property stress_level_1 timingUnits Cycles
set_interface_property stress_level_1 writeWaitTime 0
set_interface_property stress_level_1 ENABLED true
set_interface_property stress_level_1 EXPORT_OF ""
set_interface_property stress_level_1 PORT_NAME_MAP ""
set_interface_property stress_level_1 CMSIS_SVD_VARIABLES ""
set_interface_property stress_level_1 SVD_ADDRESS_GROUP ""

add_interface_port stress_level_1 avs_stress_level_address address Input 2
add_interface_port stress_level_1 avs_stress_level_readdata readdata Output 16
add_interface_port stress_level_1 avs_stress_level_write write Input 1
add_interface_port stress_level_1 avs_stress_level_writedata writedata Input 16
set_interface_assignment stress_level_1 embeddedsw.configuration.isFlash 0
set_interface_assignment stress_level_1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment stress_level_1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment stress_level_1 embeddedsw.configuration.isPrintableDevice 0

