// Custom_qsys_mm_interconnect_1.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 18.1 646

`timescale 1 ps / 1 ps
module Custom_qsys_mm_interconnect_1 (
		input  wire        sys_sdram_pll_0_sys_clk_clk,                                                 //                                               sys_sdram_pll_0_sys_clk.clk
		input  wire        sram_0_reset_reset_bridge_in_reset_reset,                                    //                                    sram_0_reset_reset_bridge_in_reset.reset
		input  wire        vga_subsystem_bus_reset_reset_bridge_in_reset_reset,                         //                         vga_subsystem_bus_reset_reset_bridge_in_reset.reset
		input  wire        vga_subsystem_pixel_dma_master_translator_reset_reset_bridge_in_reset_reset, // vga_subsystem_pixel_dma_master_translator_reset_reset_bridge_in_reset.reset
		input  wire [31:0] vga_subsystem_pixel_dma_master_address,                                      //                                        vga_subsystem_pixel_dma_master.address
		output wire        vga_subsystem_pixel_dma_master_waitrequest,                                  //                                                                      .waitrequest
		input  wire        vga_subsystem_pixel_dma_master_read,                                         //                                                                      .read
		output wire [15:0] vga_subsystem_pixel_dma_master_readdata,                                     //                                                                      .readdata
		output wire        vga_subsystem_pixel_dma_master_readdatavalid,                                //                                                                      .readdatavalid
		input  wire        vga_subsystem_pixel_dma_master_lock,                                         //                                                                      .lock
		output wire [19:0] sram_0_avalon_sram_slave_address,                                            //                                              sram_0_avalon_sram_slave.address
		output wire        sram_0_avalon_sram_slave_write,                                              //                                                                      .write
		output wire        sram_0_avalon_sram_slave_read,                                               //                                                                      .read
		input  wire [15:0] sram_0_avalon_sram_slave_readdata,                                           //                                                                      .readdata
		output wire [15:0] sram_0_avalon_sram_slave_writedata,                                          //                                                                      .writedata
		output wire [1:0]  sram_0_avalon_sram_slave_byteenable,                                         //                                                                      .byteenable
		input  wire        sram_0_avalon_sram_slave_readdatavalid                                       //                                                                      .readdatavalid
	);

	wire         vga_subsystem_pixel_dma_master_translator_avalon_universal_master_0_waitrequest;   // sram_0_avalon_sram_slave_translator:uav_waitrequest -> vga_subsystem_pixel_dma_master_translator:uav_waitrequest
	wire  [15:0] vga_subsystem_pixel_dma_master_translator_avalon_universal_master_0_readdata;      // sram_0_avalon_sram_slave_translator:uav_readdata -> vga_subsystem_pixel_dma_master_translator:uav_readdata
	wire         vga_subsystem_pixel_dma_master_translator_avalon_universal_master_0_debugaccess;   // vga_subsystem_pixel_dma_master_translator:uav_debugaccess -> sram_0_avalon_sram_slave_translator:uav_debugaccess
	wire  [31:0] vga_subsystem_pixel_dma_master_translator_avalon_universal_master_0_address;       // vga_subsystem_pixel_dma_master_translator:uav_address -> sram_0_avalon_sram_slave_translator:uav_address
	wire         vga_subsystem_pixel_dma_master_translator_avalon_universal_master_0_read;          // vga_subsystem_pixel_dma_master_translator:uav_read -> sram_0_avalon_sram_slave_translator:uav_read
	wire   [1:0] vga_subsystem_pixel_dma_master_translator_avalon_universal_master_0_byteenable;    // vga_subsystem_pixel_dma_master_translator:uav_byteenable -> sram_0_avalon_sram_slave_translator:uav_byteenable
	wire         vga_subsystem_pixel_dma_master_translator_avalon_universal_master_0_readdatavalid; // sram_0_avalon_sram_slave_translator:uav_readdatavalid -> vga_subsystem_pixel_dma_master_translator:uav_readdatavalid
	wire         vga_subsystem_pixel_dma_master_translator_avalon_universal_master_0_lock;          // vga_subsystem_pixel_dma_master_translator:uav_lock -> sram_0_avalon_sram_slave_translator:uav_lock
	wire         vga_subsystem_pixel_dma_master_translator_avalon_universal_master_0_write;         // vga_subsystem_pixel_dma_master_translator:uav_write -> sram_0_avalon_sram_slave_translator:uav_write
	wire  [15:0] vga_subsystem_pixel_dma_master_translator_avalon_universal_master_0_writedata;     // vga_subsystem_pixel_dma_master_translator:uav_writedata -> sram_0_avalon_sram_slave_translator:uav_writedata
	wire   [1:0] vga_subsystem_pixel_dma_master_translator_avalon_universal_master_0_burstcount;    // vga_subsystem_pixel_dma_master_translator:uav_burstcount -> sram_0_avalon_sram_slave_translator:uav_burstcount

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (32),
		.AV_DATA_W                   (16),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (2),
		.UAV_ADDRESS_W               (32),
		.UAV_BURSTCOUNT_W            (2),
		.USE_READ                    (1),
		.USE_WRITE                   (0),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (2),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) vga_subsystem_pixel_dma_master_translator (
		.clk                    (sys_sdram_pll_0_sys_clk_clk),                                                       //                       clk.clk
		.reset                  (vga_subsystem_pixel_dma_master_translator_reset_reset_bridge_in_reset_reset),       //                     reset.reset
		.uav_address            (vga_subsystem_pixel_dma_master_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (vga_subsystem_pixel_dma_master_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (vga_subsystem_pixel_dma_master_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (vga_subsystem_pixel_dma_master_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (vga_subsystem_pixel_dma_master_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (vga_subsystem_pixel_dma_master_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (vga_subsystem_pixel_dma_master_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (vga_subsystem_pixel_dma_master_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (vga_subsystem_pixel_dma_master_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (vga_subsystem_pixel_dma_master_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (vga_subsystem_pixel_dma_master_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (vga_subsystem_pixel_dma_master_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (vga_subsystem_pixel_dma_master_waitrequest),                                        //                          .waitrequest
		.av_read                (vga_subsystem_pixel_dma_master_read),                                               //                          .read
		.av_readdata            (vga_subsystem_pixel_dma_master_readdata),                                           //                          .readdata
		.av_readdatavalid       (vga_subsystem_pixel_dma_master_readdatavalid),                                      //                          .readdatavalid
		.av_lock                (vga_subsystem_pixel_dma_master_lock),                                               //                          .lock
		.av_burstcount          (1'b1),                                                                              //               (terminated)
		.av_byteenable          (2'b11),                                                                             //               (terminated)
		.av_beginbursttransfer  (1'b0),                                                                              //               (terminated)
		.av_begintransfer       (1'b0),                                                                              //               (terminated)
		.av_chipselect          (1'b0),                                                                              //               (terminated)
		.av_write               (1'b0),                                                                              //               (terminated)
		.av_writedata           (16'b0000000000000000),                                                              //               (terminated)
		.av_debugaccess         (1'b0),                                                                              //               (terminated)
		.uav_clken              (),                                                                                  //               (terminated)
		.av_clken               (1'b1),                                                                              //               (terminated)
		.uav_response           (2'b00),                                                                             //               (terminated)
		.av_response            (),                                                                                  //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                              //               (terminated)
		.av_writeresponsevalid  ()                                                                                   //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (20),
		.AV_DATA_W                      (16),
		.UAV_DATA_W                     (16),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (2),
		.UAV_BYTEENABLE_W               (2),
		.UAV_ADDRESS_W                  (32),
		.UAV_BURSTCOUNT_W               (2),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (1),
		.USE_WAITREQUEST                (0),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (2),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) sram_0_avalon_sram_slave_translator (
		.clk                    (sys_sdram_pll_0_sys_clk_clk),                                                       //                      clk.clk
		.reset                  (sram_0_reset_reset_bridge_in_reset_reset),                                          //                    reset.reset
		.uav_address            (vga_subsystem_pixel_dma_master_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (vga_subsystem_pixel_dma_master_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read               (vga_subsystem_pixel_dma_master_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write              (vga_subsystem_pixel_dma_master_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest        (vga_subsystem_pixel_dma_master_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (vga_subsystem_pixel_dma_master_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (vga_subsystem_pixel_dma_master_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata           (vga_subsystem_pixel_dma_master_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata          (vga_subsystem_pixel_dma_master_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock               (vga_subsystem_pixel_dma_master_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess        (vga_subsystem_pixel_dma_master_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.av_address             (sram_0_avalon_sram_slave_address),                                                  //      avalon_anti_slave_0.address
		.av_write               (sram_0_avalon_sram_slave_write),                                                    //                         .write
		.av_read                (sram_0_avalon_sram_slave_read),                                                     //                         .read
		.av_readdata            (sram_0_avalon_sram_slave_readdata),                                                 //                         .readdata
		.av_writedata           (sram_0_avalon_sram_slave_writedata),                                                //                         .writedata
		.av_byteenable          (sram_0_avalon_sram_slave_byteenable),                                               //                         .byteenable
		.av_readdatavalid       (sram_0_avalon_sram_slave_readdatavalid),                                            //                         .readdatavalid
		.av_begintransfer       (),                                                                                  //              (terminated)
		.av_beginbursttransfer  (),                                                                                  //              (terminated)
		.av_burstcount          (),                                                                                  //              (terminated)
		.av_waitrequest         (1'b0),                                                                              //              (terminated)
		.av_writebyteenable     (),                                                                                  //              (terminated)
		.av_lock                (),                                                                                  //              (terminated)
		.av_chipselect          (),                                                                                  //              (terminated)
		.av_clken               (),                                                                                  //              (terminated)
		.uav_clken              (1'b0),                                                                              //              (terminated)
		.av_debugaccess         (),                                                                                  //              (terminated)
		.av_outputenable        (),                                                                                  //              (terminated)
		.uav_response           (),                                                                                  //              (terminated)
		.av_response            (2'b00),                                                                             //              (terminated)
		.uav_writeresponsevalid (),                                                                                  //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                                               //              (terminated)
	);

endmodule
